name: "Terraform Deployment"

on:
  workflow_call:
    inputs:
      # working-directory is added to specify "terraform" directory in project source code as that's where the terraform files live.
      working-directory:
        required: false
        type: string
        default: './terraform'
      # apply-branch refers to the branch where 'terraform apply' should execute.  It defaults to the "main" branch, but calling workflow has the option to change it to a different branch to execute 'terraform apply'.
      apply-branch:
        required: false
        type: string
        default: 'main'
        
defaults:
  run:
    shell: bash

jobs:
  terraform:
    name:   Deploy terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    # important to specify the environment here so workflow knows where to deploy your artifact to.
    # default environment to "dev" if it is not passed in through workflow_dispatch manual trigger
    environment: ${{ github.event.inputs.environment || 'dev' }}

    env:
      DEPLOY_REPO: ${{ github.event.repository.name }}
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}
      REPO_OWNER: ${{ github.repository_owner }}
      
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout Code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_TO_ASSUME || vars.TERRAFORM_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION || vars.AWS_REGION }}

#       - uses: terraform-linters/setup-tflint@ba6bb2989f94daf58a4cc6eac2c1ca7398a678bf # v3.0.0
#         name: Setup TFLint
#         with:
#           tflint_version: latest

#       - name: Init TFLint
#         run: tflint --init

#       - name: Run TFLint
#         run: tflint -f compact

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@98345f2744eecaed17bdb6d7df8695de773cc4a0 # master
        with:
          directory: ${{ inputs.working-directory }}
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: reports/results.sarif # folder and name of results file
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          log_level: DEBUG # optional: set log level. Default WARNING

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@7b3bcd8d76f3cbaec0a3564e53de7c9adf00f0a7

      # extract secret from github secrets and save to a temp json file
      # to be retrieved by terraform to create secret in AWS secrets manager
      # temp file gets discarded at the end of the workflow run
      - name: Create json file from github secrets
        uses: jsdaniell/create-json@6c509494d7b009b842fb0a158852ba244920bc38
        with:
          name: "secret.json"
          json: ${{ secrets.SECRET_VALUE }}
          dir: ${{ inputs.working-directory }}

      - name: Print debug info
        run: |
          echo github actor: ${{ github.actor }}
          echo environment is ${{ github.event.inputs.environment }}
          echo branch or tag name: ${{ github.ref_name }}

      - name: Terraform Init
        id: init
        run: |
          # passes a NPM_TOKEN which has access to private repo as client app doesn't pass such credential in when calling tf reusable module.
          # credit: https://github.com/hashicorp/setup-terraform/issues/33
          git config --global url."https://oauth2:${{ secrets.NPM_TOKEN }}@github.com".insteadOf https://github.com
          rm -rf .terraform
          terraform init -backend-config='./.env/${{ github.event.inputs.environment || 'dev' }}/backend.tfvars' -upgrade=true -no-color -input=false
      
      - name: Terraform Plan
        id: plan
        run: |
          export "TF_VAR_api_key=${{ secrets.API_KEY }}"
          export TF_VAR_deploy_repo=${DEPLOY_REPO,,}
          export TF_VAR_deploy_env=${DEPLOY_ENV,,}
          export TF_VAR_repo_owner=${REPO_OWNER,,}
          export TF_VAR_pipeline_token=${{ secrets.PIPELINE_TOKEN }}
          terraform plan -input=false -var-file=.env/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars -no-color
      
      - name: Terraform Apply
        if: ${{ github.ref != 'refs/heads/destroy' }}
        id: apply
        run: |
          export "TF_VAR_api_key=${{ secrets.API_KEY }}"
          export TF_VAR_deploy_repo=${DEPLOY_REPO,,}
          export TF_VAR_deploy_env=${DEPLOY_ENV,,}
          export TF_VAR_repo_owner=${REPO_OWNER,,}
          export TF_VAR_pipeline_token=${{ secrets.PIPELINE_TOKEN }}
          terraform apply -auto-approve -input=false -var-file=.env/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
      
      - name: Terraform destroy
        # If you want to use this workflow to run terraform destroy, create a feature branch "destroy", trigger this workflow from that branch to destroy.
        if: github.ref == 'refs/heads/destroy'
        id: destroy
        run: |
          export "TF_VAR_api_key=${{ secrets.API_KEY }}"
          export TF_VAR_deploy_repo=${DEPLOY_REPO,,}
          export TF_VAR_deploy_env=${DEPLOY_ENV,,}
          export TF_VAR_repo_owner=${REPO_OWNER,,}
          export TF_VAR_pipeline_token=${{ secrets.PIPELINE_TOKEN }}
          terraform destroy -auto-approve -input=false -var-file=.env/${{ github.event.inputs.environment || 'dev' }}/terraform.tfvars
